#!/usr/bin/env python3
"""Fail-closed, resource-bounded standard-library pilot runner."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import signal
import subprocess
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from run_fixture_suite import baseline_toolchain, canonical_existing, verify_environment
from validate_receipt import ContractError, read_json, validate_receipt


UNITS = ("core", "alloc", "std")


def fail(message: str) -> None:
    raise ContractError(message)


class PilotFailure(ContractError):
    def __init__(self, classification: str, message: str) -> None:
        super().__init__(message)
        self.classification = classification


def canonical_json(value: Any) -> bytes:
    return (json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n").encode()


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def load_protocol(path: Path) -> dict[str, Any]:
    value = read_json(path)
    required = {
        "schema_version", "rap_source_commit", "rustc_commit", "cargo_commit",
        "target_triple", "unit_order", "sample_seed", "cargo_jobs",
        "runs_per_unit", "fresh_targets", "units", "sampling", "review", "thresholds",
    }
    if not isinstance(value, dict) or set(value) != required:
        fail("standard-library pilot protocol keys drifted")
    if value["schema_version"] != "unsoundaudit-v2-stdlib-pilot-protocol-v1":
        fail("standard-library pilot protocol schema drifted")
    if value["unit_order"] != list(UNITS) or value["cargo_jobs"] != 1 or value["runs_per_unit"] != 2:
        fail("standard-library pilot execution contract drifted")
    if value["fresh_targets"] != {"control": True, "scan": True}:
        fail("standard-library pilot requires fresh control and scan targets")
    if set(value["units"]) != set(UNITS):
        fail("standard-library pilot unit set drifted")
    return value


def driver_files(unit: str) -> dict[str, str]:
    if unit not in UNITS:
        fail(f"unsupported standard-library unit: {unit}")
    package = f"unsoundaudit_v2_stdlib_driver_{unit}"
    source = {
        "core": "#![no_std]\n\npub fn pilot_marker() {}\n",
        "alloc": "#![no_std]\nextern crate alloc;\n\npub fn pilot_marker() {}\n",
        "std": "pub fn pilot_marker() {}\n",
    }[unit]
    manifest = (
        "[package]\n"
        f"name = \"{package}\"\n"
        "version = \"0.0.0\"\n"
        "edition = \"2021\"\n"
        "publish = false\n\n"
        "[lib]\npath = \"src/lib.rs\"\n"
    )
    lock = f"# This file is automatically @generated by Cargo.\nversion = 3\n\n[[package]]\nname = \"{package}\"\nversion = \"0.0.0\"\n"
    return {"Cargo.toml": manifest, "Cargo.lock": lock, "src/lib.rs": source}


def write_driver(root: Path, unit: str) -> None:
    if any(root.iterdir()):
        fail("temporary driver directory must be empty")
    for relative, contents in driver_files(unit).items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(contents, encoding="utf-8")


def cargo_arguments(protocol: dict[str, Any], unit: str) -> list[str]:
    components = protocol["units"][unit]["build_std_components"]
    return [
        "-Z", f"build-std={','.join(components)}",
        "--target", protocol["target_triple"],
        "--lib", "--locked", "--jobs", "1",
    ]


def verify_rap_source_commit(repo_root: Path, commit: str) -> None:
    if len(commit) != 40 or any(character not in "0123456789abcdef" for character in commit):
        fail("pilot RAP source commit is invalid")
    ancestor = subprocess.run(
        ["git", "merge-base", "--is-ancestor", commit, "HEAD"],
        cwd=repo_root,
        stdin=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    )
    unchanged = subprocess.run(
        ["git", "diff", "--quiet", commit, "HEAD", "--", "rapx"],
        cwd=repo_root,
        stdin=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    )
    if ancestor.returncode != 0 or unchanged.returncode != 0:
        fail("current RAP source differs from the pre-registered pilot source commit")


@dataclass(frozen=True)
class ProcessResult:
    classification: str
    returncode: int | None
    elapsed_seconds: float
    max_rss_bytes: int


def parse_process_group_rss(output: str, process_group: int) -> int:
    total_kib = 0
    for line in output.splitlines():
        fields = line.split()
        if len(fields) == 3 and fields[1].isdigit() and fields[2].isdigit() and int(fields[1]) == process_group:
            total_kib += int(fields[2])
    return total_kib * 1024


def process_group_rss(pid: int) -> int:
    result = subprocess.run(
        ["ps", "-axo", "pid=,pgid=,rss="],
        stdin=subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise PilotFailure("route_failure", "process-group RSS monitor failed")
    return parse_process_group_rss(result.stdout, pid)


def terminate_group(pid: int) -> None:
    try:
        os.killpg(pid, signal.SIGTERM)
    except (ProcessLookupError, PermissionError):
        return
    time.sleep(0.2)
    try:
        os.killpg(pid, signal.SIGKILL)
    except (ProcessLookupError, PermissionError):
        pass


def run_limited(
    command: list[str],
    cwd: Path,
    environment: dict[str, str],
    log_path: Path,
    wall_time_seconds: float,
    rss_limit_bytes: int,
) -> ProcessResult:
    start = time.monotonic()
    maximum = 0
    with log_path.open("wb") as log:
        process = subprocess.Popen(
            command,
            cwd=cwd,
            env=environment,
            stdin=subprocess.DEVNULL,
            stdout=log,
            stderr=subprocess.STDOUT,
            start_new_session=True,
        )
        classification = "compiler_failure"
        try:
            while True:
                returncode = process.poll()
                elapsed = time.monotonic() - start
                if returncode is not None:
                    classification = "success" if returncode == 0 else "compiler_failure"
                    break
                current_rss = process_group_rss(process.pid)
                if current_rss <= 0:
                    returncode = process.poll()
                    if returncode is not None:
                        classification = "success" if returncode == 0 else "compiler_failure"
                        break
                    raise PilotFailure("route_failure", "running process group was absent from RSS monitor")
                maximum = max(maximum, current_rss)
                if elapsed > wall_time_seconds:
                    classification = "timeout"
                    terminate_group(process.pid)
                    returncode = process.wait()
                    break
                if maximum > rss_limit_bytes:
                    classification = "memory_limit"
                    terminate_group(process.pid)
                    returncode = process.wait()
                    break
                time.sleep(0.1)
        finally:
            if process.poll() is None:
                terminate_group(process.pid)
                process.wait()
    return ProcessResult(classification, returncode, time.monotonic() - start, maximum)


def stdlib_source_root(rust_sysroot: Path) -> Path:
    root = rust_sysroot / "lib/rustlib/src/rust"
    required = [root / "library/Cargo.lock", *(root / f"library/{unit}/Cargo.toml" for unit in UNITS)]
    if not root.is_dir() or any(not path.is_file() for path in required):
        fail("exact rust-src standard-library tree is incomplete")
    return root


def rust_kloc(unit_root: Path) -> dict[str, int | float]:
    files = sorted(path for path in unit_root.rglob("*.rs") if path.is_file() and not path.is_symlink())
    lines = sum(path.read_bytes().count(b"\n") for path in files)
    return {"rust_file_count": len(files), "rust_line_count": lines, "rust_kloc": round(lines / 1000.0, 3)}


def normalized_unit(unit: str, receipt: dict[str, Any], protocol_sha: str, source: dict[str, Any]) -> dict[str, Any]:
    return {
        "schema_version": "unsoundaudit-v2-stdlib-unit-v1",
        "unit": unit,
        "protocol_sha256": protocol_sha,
        "toolchain": {
            "cargo_supplied_rustc_commit": receipt["cargo_supplied_rustc_commit"],
            "rap_compiler_commit": receipt["rap_compiler_commit"],
            "rustc_commit": receipt["rustc_commit"],
        },
        "source_census": source,
        "finding_count": receipt["finding_count"],
        "pattern_counts": receipt["pattern_counts"],
        "findings": receipt["findings"],
    }


def select_unit_receipt(receipt_dir: Path, schema: dict[str, Any], unit: str, rustc_commit: str) -> dict[str, Any]:
    successes = []
    for path in sorted(receipt_dir.glob("*.json")):
        value = read_json(path)
        if value.get("schema_version") == "rap-unit-v2":
            successes.append(validate_receipt(value, schema))
        elif value.get("schema_version") != "rap-unit-skip-v1":
            fail(f"unrecognized pilot receipt schema: {path.name}")
    if len(successes) != 1:
        fail(f"route_failure: expected one analyzed {unit} receipt, found {len(successes)}")
    receipt = successes[0]
    if receipt["crate_name"] != unit:
        fail(f"route_failure: analyzed {receipt['crate_name']} instead of {unit}")
    for field in ("cargo_supplied_rustc_commit", "rap_compiler_commit", "rustc_commit"):
        if receipt[field] != rustc_commit:
            fail(f"route_failure: {field} differs from exact rustc commit")
    return receipt


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, required=True)
    parser.add_argument("--protocol", type=Path, required=True)
    parser.add_argument("--schema", type=Path, required=True)
    parser.add_argument("--cargo", type=Path, required=True)
    parser.add_argument("--rap-bin-dir", type=Path, required=True)
    parser.add_argument("--rust-sysroot", type=Path, required=True)
    parser.add_argument("--output-root", type=Path, required=True)
    parser.add_argument("--unit", choices=UNITS, required=True)
    args = parser.parse_args()
    output_root = args.output_root.expanduser().resolve()
    output_created = False
    try:
        repo_root = canonical_existing(args.repo_root, "repository root")
        protocol_path = canonical_existing(args.protocol, "pilot protocol")
        schema_path = canonical_existing(args.schema, "receipt schema")
        cargo = canonical_existing(args.cargo, "Cargo")
        rap_bin_dir = canonical_existing(args.rap_bin_dir, "RAP binary directory")
        rust_sysroot = canonical_existing(args.rust_sysroot, "rust sysroot")
        cargo_rapx, _ = verify_environment(repo_root, cargo, rap_bin_dir)
        protocol = load_protocol(protocol_path)
        cargo_commit, rustc_commit = baseline_toolchain(repo_root)
        if protocol["cargo_commit"] != cargo_commit or protocol["rustc_commit"] != rustc_commit:
            fail("pilot protocol toolchain differs from frozen baseline")
        verify_rap_source_commit(repo_root, protocol["rap_source_commit"])
        source_root = stdlib_source_root(rust_sysroot)
        unit_root = canonical_existing(source_root / protocol["units"][args.unit]["project_root"], "unit root")
        schema = read_json(schema_path)
        if output_root.exists():
            fail("pilot output root must not already exist")
        output_root.mkdir(parents=True, exist_ok=False)
        output_created = True
        (output_root / "logs").mkdir()
        (output_root / "receipts").mkdir()
        limits = protocol["units"][args.unit]
        executions: list[dict[str, Any]] = []
        semantic_runs: list[bytes] = []
        with tempfile.TemporaryDirectory(prefix=f"rapx-stdlib-driver-{args.unit}.") as driver_text:
            driver = Path(driver_text).resolve()
            write_driver(driver, args.unit)
            arguments = cargo_arguments(protocol, args.unit)
            for phase, run_number in [("control", 0), ("scan", 1), ("scan", 2)]:
                with tempfile.TemporaryDirectory(prefix=f"rapx-stdlib-{args.unit}-{phase}.") as target_text:
                    target = Path(target_text).resolve()
                    environment = os.environ.copy()
                    environment["CARGO_BUILD_JOBS"] = "1"
                    environment["CARGO_TARGET_DIR"] = str(target)
                    if phase == "control":
                        command = [str(cargo), "check", *arguments]
                    else:
                        receipt_dir = output_root / "receipts" / f"run-{run_number}"
                        receipt_dir.mkdir()
                        environment["UNSOUND_SCANNER_RAP_JSON_DIR"] = str(receipt_dir)
                        environment["UNSOUND_SCANNER_PROJECT_ROOT"] = str(unit_root)
                        command = [str(cargo_rapx), "rapx", "-unsoundaudit", "--", *arguments]
                    result = run_limited(
                        command, driver, environment, output_root / "logs" / f"{phase}-{run_number}.log",
                        limits["wall_time_seconds"], limits["rss_limit_bytes"],
                    )
                    executions.append({
                        "phase": phase, "run": run_number, "classification": result.classification,
                        "returncode": result.returncode, "elapsed_seconds": round(result.elapsed_seconds, 3),
                        "max_rss_bytes": result.max_rss_bytes,
                    })
                    if result.classification != "success":
                        raise PilotFailure(result.classification, f"{phase} {run_number} failed")
                    if phase == "scan":
                        try:
                            receipt = select_unit_receipt(receipt_dir, schema, args.unit, rustc_commit)
                        except (ContractError, OSError) as error:
                            raise PilotFailure("route_failure", str(error)) from error
                        normalized = canonical_json(normalized_unit(args.unit, receipt, sha256(protocol_path), rust_kloc(unit_root)))
                        semantic_runs.append(normalized)
        if len(semantic_runs) != 2 or semantic_runs[0] != semantic_runs[1]:
            raise PilotFailure("route_failure", "nondeterminism: normalized receipts differ")
        (output_root / f"{args.unit}.normalized.json").write_bytes(semantic_runs[0])
        (output_root / f"{args.unit}.execution.json").write_bytes(canonical_json({
            "schema_version": "unsoundaudit-v2-stdlib-execution-v1",
            "unit": args.unit,
            "status": "success",
            "protocol_sha256": sha256(protocol_path),
            "executions": executions,
            "raw_logs_committed": False,
        }))
        return 0
    except (ContractError, OSError, ValueError) as error:
        if output_created and output_root.is_dir() and not (output_root / f"{args.unit}.normalized.json").exists():
            classification = error.classification if isinstance(error, PilotFailure) else "route_failure"
            (output_root / f"{args.unit}.failure.json").write_bytes(canonical_json({
                "schema_version": "unsoundaudit-v2-stdlib-failure-v1",
                "unit": args.unit,
                "status": "failure",
                "classification": classification,
                "raw_logs_committed": False,
            }))
        print(f"standard-library pilot error: {error}", file=os.sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
